version: '3.8'

services:
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_URL=postgresql+psycopg://postgres:test_password@postgres:5432/postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=8080
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: test_password
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
